version: "2"
services:

  node:
    image: tezos/tezos:latest
    hostname: node
    command: tezos-node
    ports:
      - 9732:9732
    expose:
      - '8732'
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: on-failure

  baker:
    image: tezos/tezos:latest
    hostname: baker
    command: tezos-baker
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

  endorser:
    image: tezos/tezos:latest
    hostname: endorser
    command: tezos-endorser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

  accuser:
    image: tezos/tezos:latest
    hostname: accuser
    command: tezos-accuser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

volumes:
  node_data:
  client_data:
