version: '3'

volumes:
  client_data:
  node_data:

services:
  node:
    image: tezos/tezos:zeronet
    hostname: node
    command: tezos-node
    ports:
      - 19732:19732
    expose:
      - '8732'
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: on-failure

  ## Duplicate the `baker/endorser/accuser` containers for each PROTOCOL
  ## in file `active_protocol_versions`
  baker-alpha:
    image: tezos/tezos:zeronet
    hostname: baker-alpha
    environment:
      - PROTOCOL=alpha
    command: tezos-baker
    links:
      - node
    volumes:
      - node_data:/var/run/tezos/node:ro
      - client_data:/var/run/tezos/client
    restart: on-failure

  endorser-alpha:
    image: tezos/tezos:zeronet
    hostname: endorser-alpha
    environment:
      - PROTOCOL=alpha
    command: tezos-endorser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure

  accuser-alpha:
    image: tezos/tezos:zeronet
    hostname: accuser-alpha
    environment:
      - PROTOCOL=alpha
    command: tezos-accuser
    links:
      - node
    volumes:
      - client_data:/var/run/tezos/client
    restart: on-failure
